ENV['SWIFT_VERSION'] = '5'
target 'mymodule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  use_modular_headers!
  pod 'GeoSpark'
  # Pods for GeoSparkRNExample
end
